### ISSUE TITLE
APP SIZE CAN REDUCE VIA USING DYNAMIC ACTIVITY

### ISSUE THREAD

**Issue by alamin-karno** [zobayerdev/BD_Education_Result#2]
Recently I downloaded this repository & make some changes. But I have figured out that this app size can be reduced using dynamic activity. 

So, I want to contribute to this project. But only I will continue contributing to this project if this repository is under 'hackoctoberfest'. So if you want to improve this open-source project so, please add this topic.

**Comment by zobayerdev** [comment]
ok sure.

**Comment by alamin-karno** [comment]
ALREADY SUBMITTED THE REDUCED CODE.
